# Generated by Django 4.1 on 2022-12-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Namn')),
                ('email', models.EmailField(help_text='För bekräftelse/kvittens', max_length=254, verbose_name='E-postadress')),
                ('phone', models.IntegerField(help_text='För bekräftelse/kvittens', verbose_name='Telefonnummer')),
                ('is_coming', models.CharField(choices=[('yes', 'Ja!'), ('no', 'Nej, jag/vi kan tyvärr inte komma')], max_length=4, verbose_name='Kommer ni på bröllopet?')),
                ('is_partying', models.CharField(choices=[('yes', 'Ja!'), ('no', 'Nej, jag/vi deltar endast vid ceremonin')], max_length=4, verbose_name='Stannar ni till middagen?')),
                ('people_count', models.SmallIntegerField(verbose_name='Antal personer')),
                ('children_count', models.SmallIntegerField(verbose_name='Varav barn')),
                ('diet', models.TextField(verbose_name='Specialkost')),
                ('camping', models.CharField(choices=[('tent', 'Ja, i tält'), ('rv', 'Ja, i Husvagn'), ('no', 'Nej, ingen campingplats')], max_length=4, verbose_name='Campar ni vid Österå Bystuga?')),
                ('note', models.TextField(verbose_name='Övrig kommentar')),
                ('consent', models.BooleanField(verbose_name='Ja, brudparet får spara mina uppgifter fram tills juli 2023 för att skicka information om bröllopet')),
                ('verified', models.BooleanField(verbose_name='Kvittens skickad')),
            ],
            options={
                'verbose_name': 'Svar på inbjudan',
                'verbose_name_plural': 'Svar på inbjudan',
            },
        ),
    ]
