# Generated by Django 4.1 on 2022-12-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitation", "0002_alter_invitationresponse_children_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitationresponse",
            name="camping",
            field=models.CharField(
                choices=[
                    ("tent", "Ja, i tält"),
                    ("rv", "Ja, i Husvagn"),
                    ("no", "Nej, ingen campingplats"),
                ],
                default="no",
                max_length=4,
                verbose_name="Campar ni vid Österå Bystuga?",
            ),
        ),
        migrations.AlterField(
            model_name="invitationresponse",
            name="children_count",
            field=models.SmallIntegerField(blank=True, verbose_name="Antal barn"),
        ),
        migrations.AlterField(
            model_name="invitationresponse",
            name="is_coming",
            field=models.CharField(
                choices=[("yes", "Ja!"), ("no", "Nej, jag/vi kan tyvärr inte komma")],
                default="yes",
                max_length=4,
                verbose_name="Kommer ni på bröllopet?",
            ),
        ),
        migrations.AlterField(
            model_name="invitationresponse",
            name="is_partying",
            field=models.CharField(
                choices=[
                    ("yes", "Ja!"),
                    ("no", "Nej, jag/vi deltar endast vid ceremonin"),
                ],
                default="yes",
                max_length=4,
                verbose_name="Stannar ni till middagen och festen?",
            ),
        ),
        migrations.AlterField(
            model_name="invitationresponse",
            name="people_count",
            field=models.SmallIntegerField(blank=True, verbose_name="Antal personer"),
        ),
    ]
