# Generated by Django 4.1 on 2022-12-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invitation", "0003_alter_invitationresponse_camping_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitationresponse",
            name="children_count",
            field=models.SmallIntegerField(
                blank=True, null=True, verbose_name="Antal barn"
            ),
        ),
        migrations.AlterField(
            model_name="invitationresponse",
            name="diet",
            field=models.TextField(blank=True, null=True, verbose_name="Specialkost"),
        ),
        migrations.AlterField(
            model_name="invitationresponse",
            name="note",
            field=models.TextField(
                blank=True, null=True, verbose_name="Övrig kommentar"
            ),
        ),
        migrations.AlterField(
            model_name="invitationresponse",
            name="people_count",
            field=models.SmallIntegerField(
                blank=True, null=True, verbose_name="Antal personer"
            ),
        ),
    ]
